# Default initial positions for the UR5 with Robotiq 2F-85 gripper.

initial_positions:
  shoulder_pan_joint: -3.2283
  shoulder_lift_joint: -1.4927
  elbow_joint: 0.0868
  wrist_1_joint: -1.4232
  wrist_2_joint: -6.2137
  wrist_3_joint: 1.6315
  robotiq_85_left_knuckle_joint: 0.0
